
name: Build and Deploy Code

on: [push, pull_request]



jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: e405fdc9564a1a5e0443fcbcbd3b26946458a26c3ec20e64ccf1f9ca1a13a253
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: setting up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installing dependencies
        run: pip install -r requirements.txt
      - name: running tests
        run: |
          pip install pytest
          pytest
